//! gRPC transport for AresaDB v2 Raft RPCs.
//!
//! See the crate README for the full design brief. The short story:
//!
//! * `pb` — code generated by `tonic_build` from `proto/raft.proto`.
//! * `codec` — bincode helpers that match the `is_error` convention
//!   on every response type.
//! * `server` — [`RaftGrpcServer`] adapts a `openraft::Raft` handle
//!   to the generated tonic service trait.
//! * `client` — [`GrpcRaftNetwork`] implements `RaftNetworkFactory`
//!   so an `openraft::Raft` on this end can replicate to peers.
//!
//! Everything funnels through the same `TypeConfig` exposed by
//! `aresadb_raft`, which is the pivot that ties the transport, log
//! store, and state machine together.

pub mod client;
pub mod codec;
pub mod server;

pub mod pb {
    //! Generated from `proto/raft.proto`. The module name matches the
    //! protobuf `package` declaration.
    tonic::include_proto!("aresadb.raft.v1");
}

pub use client::{GrpcRaftNetwork, PeerDirectory, StaticPeerDirectory, SINGLETON_RAFT_GROUP_ID};
pub use server::{RaftDirectory, RaftGrpcServer, SingletonRaftDirectory};
